version: '1.0'
name: hexo-oss-deploy
displayName: HexoTest
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: deploy-stage
    displayName: Deploy Stage
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: deploy-step
        displayName: Deploy Step
        nodeVersion: 14.16.0
        commands:
          - set -e
          - node -v
          - npm -v
          - npm install
          - npm run clean
          - npm run deploy
          - ''
