version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
variables:
  global:
    - REPO
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./public
          - ''
          - npm install hexo-cli -g
          - ''
          - hexo version
          - npm install
          - npm install hexo-deployer-git --save
          - git config --global user.email "451447840@qq.com"
          - git config --global user.name "luoyezadi"
          - npm run config deploy.repo $REPO
          - rm -rf .deploy_git
          - git config --global core.autocrlf false
          - echo "hexo deploy"
          - hexo clean && hexo g && hexo d
          - ''
          - ''
        strategy: {}
